version: "3.8"
services:
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pollify
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass redispassword
    volumes:
      - redis:/data
volumes:
  postgres:
    driver: local
  redis:
    driver: local
