name: Code Quality
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun install

      - name: Generate prisma types
        run: bun run turbo run db:generate

      - name: Type Check
        run: bun run typecheck

      - name: Lint
        run: bun run lint
