name: Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun install

      - name: Test
        env:
          PORT: 3000
          ORIGIN_URL: http://localhost:3000
          FRONTEND_URL: http://localhost:3000
          REDIS_URL: ${{ secrets.REDIS_URL }}
        run: bun run test
